<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'metrix_id' => '',
    'Active' => 'Активен',
    'BatteryLevel' => 'Заряд батареи',
    'Counter' => 'Счетчик',
    'Deactivated' => 'Выполнен',
    'Disconnect' => 'Потеря связи',
    'InWork' => 'В работе',
    'LastOnline' => 'последний выход на связь',
    'Leak' => 'Утечка',
    'LowBalance' => 'Недостаточно средсв на счету',
    'LowBatteryLevel' => 'Разряд батареи',
    'Magnet' => 'Магнит',
    'MagnetUsed' => 'Использование Магнита',
    'Modem' => 'Модем',
    'Tamper' => 'Взлом',
    'Waiting' => 'Ожидание',
    'address' => 'Адрес',
    'cause' => 'Причина',
    'deviceType' => 'Тип оборудования',
    'modemNumber' => '№ модема',
    'onAccount' => 'на счету',
    'recommended' => 'рекомендуемый',
    'status' => 'Состояние',
    'time' => 'Время',
    'type' => 'Тип',
];
