<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Desctription' => '',
    'Description' => '@@Пояснения@@',
    ': was- {text2} became- {text}' => ': было- {text2} стало- {text}',
    'Adding' => 'Добавление',
    'Address' => 'адрес',
    'Address2' => 'адреса',
    'Alert' => 'Предупреждение',
    'Alert2' => 'Предупреждения',
    'Changes' => 'Изменения',
    'Correction' => 'Коррекция',
    'Correction2' => 'Коррекции',
    'Corrector' => 'Корректор',
    'Counter' => 'Счетчик',
    'CounterType' => 'Тип Счетчика',
    'Created_at' => 'Время и Дата',
    'Delay' => 'Продолжительность',
    'Documents' => 'Документа',
    'Edit' => 'Редактирования',
    'Editing' => 'Редактирование',
    'Events Log' => 'Журнал Событий',
    'EventsLog' => 'Журнал Событий',
    'Id' => 'Id',
    'Login' => 'Вход в систему',
    'Logout' => 'Выход из системы',
    'Modem' => 'Модем',
    'OnOffRtMode' => 'Включен\\выключен реалтайм режим',
    'Region' => 'Регион',
    'Rmodule' => 'Радиомодуль',
    'Type' => 'Тип',
    'User' => 'Ф.И.О.',
    'User2' => 'Пользователь',
    'User3' => 'Пользователя',
    'UserAction' => 'Действие',
    'Values' => 'Значения',
    'WentOnPage' => 'Перешел на страницу',
];
