<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Calendar' => '',
    'Contract' => '',
    'Traffic' => '',
    'consump' => 'Расход',
    'currentDate' => '',
    'invoice' => '',
    'Accidents' => 'Аварии',
    'Charts' => 'Графики',
    'ConsumpCurrentDay' => 'Потребление за день',
    'ConsumpDayAverage' => 'Среднесуточный расход',
    'ConsumpMonth' => 'Потребление за месяц',
    'ConsumpPastDay' => 'Потребление за предыдущий день',
    'Contractor' => 'Контрагент',
    'Counter' => 'Счетчик',
    'GSM modem' => 'GSM modem',
    'Indication' => 'Показания',
    'Map' => 'Карта',
    'Monitoring' => 'Мониторинг',
    'Options' => 'Настройки',
    'Reports' => 'Отчеты',
    'account' => 'Лицевой счет',
    'alerts_log' => 'Лог предупреждений',
    'balance' => 'На счету',
    'chose_address' => 'Выберите адрес',
    'close' => 'закрыт',
    'close_valve' => 'Закрыть клапан',
    'command_send_in' => ' команда послана в ',
    'counter_number' => '№ счетчика',
    'created_at' => 'создано',
    'currentIndications' => 'Текушие показания',
    'current_indication' => 'Текушие показания',
    'download' => 'Скачать',
    'export_csv' => 'Экспорт в CSV',
    'export_dbf' => 'Экспорт в DBF',
    'fulladdress' => 'Адрес',
    'geo_location_id' => 'Адрес',
    'history_indiations' => 'История показаний',
    'metrix_list' => 'Список  счетчиков',
    'modem' => 'Модем',
    'modem_number' => '№ модема',
    'open' => 'открыт',
    'open_valve' => 'Открыть клапан',
    'period_begin' => 'Начало периода',
    'period_end' => 'Конец периода',
    'phone' => 'Номер телефона',
    'report_for' => 'Отчет за',
    'sform' => 'Сформировать',
    'signal_level' => 'Уровень сигнала',
    'status' => 'Состояние',
    'time_on_line' => 'Последний выход на связь',
    'updated_at' => 'изменено в ',
    'valve_status' => 'Состояние клапана',
    'view' => 'просмотр',
    'modem_options'=>'Настройки модема',
    'update_interval'=>'Интервал обновления данных (В МИНУТАХ!)',
    'Query send in {time}'=>'Запрос послан в  {time}',
];
