<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Date' => 'Дата',
    'Delay' => 'Задержка',
    'Modem number' => '№ модема',
    'Send' => 'отправить',
    'Send on' => ' отправлено в ',
    'Time' => 'Время',
    '% Of the limit applied <br> limit this month' => '% от лимита использовано <br> Лимит текущего месяца',
    'Accidents' => 'Аварии',
    'Accidents in the past month' => 'Аварии за текуший месяц',
    'Consumption for the current day' => 'Потребление за тек. день',
    'Consumption for the month' => 'Потребление за месяц',
    'Consumption over the past day' => 'Потребление за прошлый день',
    'Diagnostic Comms' => 'Диагностика',
    'Interventions' => 'Вмешательсва',
    'Off' => 'Выкл',
    'On' => 'Вкл',
    'Online mode' => 'Режим реального времени',
    'Pressure' => 'Давление',
    'Temperature' => 'Температура',
    'Volume consumption' => 'Объемный расход',
    'not ready' => 'не готов',
    'online' => ' на связи ',
    'ready' => 'готов',
];
