<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cycle' => 'Выходов на связь',
    'dayTrafficInSum' => 'Дневной входящий трафик , байт',
    'dayTrafficOutSum' => 'Дневной исходящий трафик , байт',
    'lastTrafficInSum' => 'Последний входящий трафик , байт',
    'lastTrafficOutSum' => 'Последний исходящий трафик , байт',
    'monthTrafficInSum' => 'Месячный входящий трафик , байт',
    'monthTrafficOutSum' => 'Месячный исходящий трафик , байт',
    'temperature' => '',
    'Accidents' => 'Аварии',
    'Action' => 'Дейсвие',
    'Address' => 'Адрес',
    'Balance' => 'Баланс',
    'Balance history' => 'История баланса',
    'Busy' => 'Занят',
    'Calculator number' => '№ Вычислителя',
    'Charts' => 'Графики',
    'Combit' => 'Комбыт',
    'Company' => 'Предприятие',
    'Company name' => 'Наименование предприятия',
    'Connect log' => 'Журнал соединений',
    'ConsumpTotal' => 'Общее потребление',
    'Consumption on day' => 'Потребление за сутки',
    'Consumption on prev day' => 'Потребление за предыдушие сутки',
    'Contract' => 'Договор',
    'Contract hour' => 'Контрактный час',
    'Contractor' => 'Контрагент',
    'CreateReport' => 'Создать отчет',
    'Current pressure' => 'Текущее давление',
    'Current temperature' => 'Текущая температура',
    'Cycle ' => 'Количество выходов на связь',
    'Daily' => 'Суточный',
    'Daily report' => 'Суточный отчет',
    'Data for' => 'Данные на',
    'Date' => 'Дата',
    'Day report' => 'дневной отчет',
    'Diagnostic Comms' => 'Диагностика',
    'Disconnect' => 'Нет связи',
    'Export in 1C' => 'Экспорт в 1C',
    'Export in Excel' => 'Экспорт в Газолин',
    'Export in Gasoline' => 'Экспорт в Эксель',
    'GRS' => 'ГРС',
    'GSM modem' => 'GSM модем',
    'History Limits' => 'История Лимитов',
    'HouseMetering' => 'Общедомовой узел учета',
    'Indication' => 'Показания ',
    'Indications table' => 'Таблица показаний',
    'Industry' => 'Промышленность',
    'Interventions' => 'Вмешательсва',
    'Last online' => 'Последний выход на связь',
    'Limit of this month' => 'Лимит текущего месяца',
    'Limit the next month' => 'Лимит следующего  месяца',
    'Limits of gas consumption' => 'Лимит расхода газа',
    'List of correctors' => 'Список Корректоров',
    'Map' => 'Карта',
    'Modem' => 'Модем',
    'Monitoring' => 'Мониторинг',
    'Monthly' => 'Месячный',
    'Online' => 'На связи',
    'Phone number' => 'Телефонный номер',
    'Photo' => 'Фото',
    'Pressure' => 'давление',
    'Reports' => 'Отчеты',
    'Request for daily report' => 'Запрос на получение дневного отчета',
    'Request for forced debiting' => 'Запрос принудительного списания',
    'Request package name' => 'Запрос названия пакета',
    'Request to the corrector' => 'Запросы к корректору',
    'Request to the simcard' => 'Запросы к sim-карте',
    'Requests' => 'Запросы',
    'SIM' => 'SIM',
    'SMS history' => 'История SMS',
    'Signal level' => 'Уровень сигнала',
    'Sleep' => 'В ожидании',
    'Status' => 'Состояние',
    'Temperature' => 'температура',
    'The query is executed expect an answer' => 'Запрос выполняется ожидайте ответа',
    'Update time' => 'время обновления',
    'View' => 'просмотр',
    'Weekly' => 'Недельный',
    'calculate' => 'Рассчитать',
    'hw_status' => 'Состояние',
];
