<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активен',
    'Deactivated' => 'Неактивен',
    'Region' => 'Область',
    'Waiting_email_approve' => 'Подтверждение Email',
    'add_bot_in_contact_list' => 'Добавить бота в список контактов',
    'address' => 'Адрес',
    'change_password' => 'Изменить пароль',
    'chose_region' => 'Выберите город',
    'email' => '',
    'enable_email_notif' => 'Включить отправку оповещений на имейл',
    'enable_telegram_notif' => 'Включить отправку оповещений в телеграм',
    'facility' => 'Предприятие',
    'first_name' => 'Имя',
    'geo_location_id' => 'Город',
    'inn' => 'ИНН',
    'last_name' => 'Фамилия',
    'legal_address' => 'Юридический адрес',
    'main' => 'Основное',
    'new_password' => 'Новый пароль',
    'nick_name' => 'Никнейм',
    'notification_types' => 'Типы уведомлений',
    'notifications' => 'Уведомления',
    'password' => 'Пароль',
    'password_repeat' => 'Повторите пароль',
    'reg_date' => 'дата регистрации',
    'role' => 'роль',
    'roles' => 'Роли',
    'status' => 'состояние',
    'telegram_id' => '',
    'user_edit' => 'Редактировать пользователя',
    'users' => 'Пользователи',
    'language_id'=>'Язык'
];
