<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Deactivated' => '',
    'Region' => '',
    'Waiting_email_approve' => '',
    'add_bot_in_contact_list' => '',
    'address' => '',
    'change_password' => '',
    'chose_region' => '',
    'email' => '',
    'enable_email_notif' => '',
    'enable_telegram_notif' => '',
    'facility' => '',
    'first_name' => '',
    'geo_location_id' => '',
    'inn' => '',
    'language_id' => '',
    'last_name' => '',
    'legal_address' => '',
    'main' => '',
    'new_password' => '',
    'nick_name' => '',
    'notification_types' => '',
    'notifications' => '',
    'password' => '',
    'password_repeat' => '',
    'reg_date' => '',
    'role' => '',
    'roles' => '',
    'status' => '',
    'telegram_id' => '',
    'user_edit' => '',
    'users' => '',
];
