<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ': was- {text2} became- {text}' => '',
    'Adding' => '',
    'Address' => '',
    'Address2' => '',
    'Alert' => '',
    'Alert2' => '',
    'Changes' => '',
    'Correction' => '',
    'Correction2' => '',
    'Corrector' => '',
    'Counter' => '',
    'CounterType' => '',
    'Created_at' => '',
    'Delay' => '',
    'Desctription' => '',
    'Documents' => '',
    'Edit' => '',
    'Editing' => '',
    'Events Log' => '',
    'EventsLog' => '',
    'Id' => '',
    'Login' => '',
    'Logout' => '',
    'Modem' => '',
    'OnOffRtMode' => '',
    'Region' => '',
    'Rmodule' => '',
    'Type' => '',
    'User' => '',
    'User2' => '',
    'User3' => '',
    'UserAction' => '',
    'Values' => '',
    'WentOnPage' => '',
];
