<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accidents' => '',
    'Calendar' => '',
    'Charts' => '',
    'ConsumpCurrentDay' => '',
    'ConsumpDayAverage' => '',
    'ConsumpMonth' => '',
    'ConsumpPastDay' => '',
    'Contract' => '',
    'Contractor' => '',
    'Counter' => '',
    'GSM modem' => '',
    'Indication' => '',
    'Map' => '',
    'Monitoring' => '',
    'Options' => '',
    'Reports' => '',
    'Traffic' => '',
    'account' => '',
    'alerts_log' => '',
    'balance' => '',
    'chose_address' => '',
    'close' => '',
    'close_valve' => '',
    'command_send_in' => '',
    'consump' => '',
    'counter_number' => '',
    'created_at' => '',
    'currentDate' => '',
    'currentIndications' => '',
    'current_indication' => '',
    'download' => '',
    'export_csv' => '',
    'export_dbf' => '',
    'fulladdress' => '',
    'geo_location_id' => '',
    'history_indiations' => '',
    'invoice' => '',
    'metrix_list' => '',
    'modem' => '',
    'modem_number' => '',
    'open' => '',
    'open_valve' => '',
    'period_begin' => '',
    'period_end' => '',
    'phone' => '',
    'report_for' => '',
    'sform' => '',
    'signal_level' => '',
    'status' => '',
    'time_on_line' => '',
    'updated_at' => '',
    'valve_status' => '',
    'view' => '',
];
