<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'აქტიურად',
    'BatteryLevel' => 'ბატარეის მუხტი',
    'Counter' => 'დახლი',
    'metrix_id' => '№ დახლი',
    'Deactivated' => 'დაასრულა',
    'Disconnect' => 'კავშირის დაკარგვა',
    'InWork' => 'მუშაობა',
    'LastOnline' => 'last online',
    'Leak' => 'გაჟონვის',
    'LowBalance' => 'არასაკმარისი თანხების ანგარიშზე',
    'LowBatteryLevel' => 'დაბალი ბატარეის',
    'Magnet' => 'მაგნიტი',
    'MagnetUsed' => 'გამოყენება მაგნიტი',
    'Modem' => 'მოდემი',
    'Tamper' => 'დაცულია უდიერად',
    'Waiting' => 'მოლოდინი',
    'address' => 'მისამართი',
    'cause' => 'მიზეზი',
    'deviceType' => 'მოწყობილობის ტიპი',
    'modemNumber' => 'მოდემის ნომერი',
    'onAccount' => 'თანხა ანგარიშზე',
    'recommended' => 'რეკომენდირებული',
    'status' => 'მდგომარეობა',
    'time' => 'დრო',
    'type' => 'ტიპი',
];
