<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Desctription' => 'აღწერა',
    ': was- {text2} became- {text}' => '',
    'Adding' => 'გარდა ამისა,',
    'Address' => 'მისამართი',
    'Address2' => 'მისამართი',
    'Alert' => 'გაფრთხილება',
    'Alert2' => 'გაფრთხილებები',
    'Changes' => 'ცვლილებები',
    'Correction' => 'შესწორება',
    'Correction2' => 'შესწორება',
    'Corrector' => 'კორექტორი',
    'Counter' => 'კონტრშეტევებზე',
    'CounterType' => 'ტიპი კონტრშეტევებზე',
    'Created_at' => 'თარიღი და დრო',
    'Delay' => 'ხანგრძლივობა',
    'Documents' => 'დოკუმენტი',
    'Edit' => 'რედაქტირება',
    'Editing' => 'რედაქტირება',
    'Events Log' => 'თარიღის შესვლა',
    'EventsLog' => 'თარიღის შესვლა',
    'Id' => 'Id',
    'Login' => 'წევრი შესვლა',
    'Logout' => 'გამოდიხართ სისტემიდან',
    'Modem' => 'მოდემი',
    'OnOffRtMode' => 'On \\ off რეალურ დროში რეჟიმი',
    'Region' => 'რეგიონში',
    'Rmodule' => 'რადიო',
    'Type' => 'ტიპი',
    'User' => 'მომხმარებელს',
    'User2' => 'მომხმარებელს',
    'User3' => 'მომხმარებელს',
    'UserAction' => 'აქცია',
    'Values' => 'მნიშვნელობის',
    'WentOnPage' => '',
];
