<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Calendar' => '',
    'Contract' => '',
    'Traffic' => '',
    'currentDate' => '',
    'invoice' => '',
    'consump_period' => '@@მოხმარების პერიოდი@@',
    'Accidents' => 'ავარიის',
    'Charts' => 'დიაგრამები',
    'ConsumpCurrentDay' => 'მოხმარების პოსტი დღეში',
    'ConsumpDayAverage' => 'საშუალო ყოველდღიური მოხმარების',
    'ConsumpMonth' => 'თვიური მოხმარება',
    'ConsumpPastDay' => 'მოხმარების წინა დღეს',
    'Contractor' => 'კონტრაქტორი',
    'Counter' => 'დახლი',
    'GSM modem' => 'GSM modem',
    'Indication' => 'მრიცხველის ჩვენების',
    'Map' => 'რუკა',
    'Monitoring' => 'მონიტორინგის',
    'Options' => 'პარამეტრები',
    'Reports' => 'ანგარიშები',
    'account' => 'პირადი ანგარიში',
    'alerts_log' => 'სია გაფრთხილება',
    'balance' => 'ბანკში',
    'chose_address' => 'აირჩიეთ მისამართი',
    'close' => 'დახურულია',
    'close_valve' => 'დახურვა სარქველი',
    'command_send_in' => ' ბრძანება ეგზავნება ',
    'consump' => 'მოხმარების',
    'counter_number' => '№ დახლი',
    'created_at' => 'შეიქმნა',
    'currentIndications' => 'მიმდინარე აღნიშვნის',
    'current_indication' => 'მიმდინარე აღნიშვნის',
    'download' => 'ჩამოტვირთვა',
    'export_csv' => 'ექსპორტი CSV',
    'export_dbf' => 'ექსპორტი DBF',
    'fulladdress' => 'მისამართი',
    'geo_location_id' => 'მისამართი',
    'history_indiations' => 'ისტორია საზომი',
    'metrix_list' => 'სია დახლი',
    'modem' => 'მოდემი',
    'modem_number' => 'მოდემის ნომერი',
    'open' => 'გაიხსნა',
    'open_valve' => 'გახსნა სარქველი',
    'period_begin' => 'პერიოდის დასაწყისში',
    'period_end' => 'ბოლოს პერიოდში',
    'phone' => 'ტელეფონის ნომერი',
    'report_for' => 'ანგარიში',
    'sform' => 'გენერირება',
    'signal_level' => 'სიგნალი დონეზე',
    'status' => 'სტატუსი',
    'time_on_line' => 'last online',
    'updated_at' => 'შეიცვალა ',
    'valve_status' => 'სარქველი',
    'view' => 'ნახეთ',
    'modem_options'=>'მოდემი პარამეტრები',
    'update_interval'=>'ინტერვალი მონაცემების განახლება (წუთი)',
    'Query send in {time}'=>' თხოვნა იგზავნება {time}',
];
