<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Average pressure, kgf / m<sup>2</sup>' => 'საშუალო წნევის, kgf / m<sup>2</sup>',
    'Average temperature C<sup>o</sup>' => 'საშუალო ტემპერატურა C<sup>o</sup>',
    'Consumption over the past day s.c. ,m<sup>3</sup>' => 'მოხმარების ბოლო დღეს სტანდარტულ პირობებს ,m<sup>3</sup> ',
    'Consumption over the past hour s.c. ,m<sup>3</sup>' => 'მოხმარების ბოლო საათი სტანდარტულ პირობებს ,м<sup>3</sup>',
    'Consumption per day s.c. ,m<sup>3</sup>' => 'მოხმარების დღეში სტანდარტული პირობები ,м<sup>3</sup>',
    'Consumption per hour s.c. ,m<sup>3</sup>' => 'მოხმარების საათში სტანდარტული პირობები ,м<sup>3</sup>',
    'Diameter ND , mm' => 'დიამეტრი ავიწროებს მოწყობილობა ,мм',
    'Diameter Tube, mm' => 'დიამეტრის მილები ,мм',
    'Differential pressure, kgf / m<sup>2</sup>' => 'წნევის ვარდნა, kgf / m<sup>2</sup>',
    'Pressure, kgf / m<sup>2</sup>' => 'ზეწოლა, kgf / m<sup>2</sup>',
    'Pseudocritical pressure, kgf / m<sup>2</sup>' => 'pseudocritical ზეწოლა, kgf / m<sup>2</sup>',
    'Pseudocritical temperature C<sup>o</sup>' => 'pseudocritical ტემპერატურა, C<sup>o</sup> ',
    'Temperature C<sup>o</sup>' => 'ტემპერატურა C<sup>o</sup>',
    'Updated at' => 'განახლებულია',
    'Volume consumption r.c.' => 'მოცულობითი ნაკადის ფაქტობრივი მდგომარეობა',
    'Volume consumption s.c.' => 'ნაკადებსა სტანდარტული პირობები',
];
