<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'dayTrafficInSum' => ' დღის შემომავალი ტრაფიკის, ბაიტად',
    'dayTrafficOutSum' => ' დღის გამავალი ტრაფიკის, ბაიტად',
    'lastTrafficInSum' => ' ბოლო შემომავალი ტრაფიკის, ბაიტად',
    'lastTrafficOutSum' => ' ბოლო გამავალი ტრაფიკის, ბაიტად',
    'monthTrafficInSum' => ' ყოველთვიური შემომავალი ტრაფიკის, ბაიტად',
    'monthTrafficOutSum' => ' ყოველთვიური გამავალი ტრაფიკის ბაიტად',
    'Cycle' => 'რაოდენობის კავშირები',
    'Data for' => '',
    'Last online' => '',
    'Online' => '',
    'SIM' => '',
    'SMS history' => '',
    'The query is executed expect an answer' => '',
    'Accidents' => 'უბედური შემთხვევა',
    'Action' => 'ეფექტი',
    'Address' => 'მისამართი',
    'Balance' => 'თანხების ანგარიშზე',
    'Balance history' => 'თანხების ანგარიშზე',
    'Busy' => 'დაკავებულია',
    'Calculator number' => 'სერიული ნომერი კალკულატორი',
    'Charts' => 'დიაგრამები',
    'Combit' => 'პირები',
    'Company' => 'კომპანია',
    'Company name' => 'კომპანია',
    'Connect log' => 'დაკავშირება ჟურნალი',
    'ConsumpTotal' => 'საერთო მოხმარების',
    'Consumption on day' => 'მოხმარების დღეში',
    'Consumption on prev day' => 'მოხმარების გასული დღე',
    'Contract' => 'კონტრაქტის',
    'Contract hour' => 'ხელშეკრულება საათობრივად',
    'Contractor' => 'კონტრაქტორი',
    'CreateReport' => 'ანგარიშის შექმნა',
    'Current pressure' => 'მიმდინარე ზეწოლის',
    'Current temperature' => 'მიმდინარე ტემპერატურა',
    'Cycle ' => 'ციკლი',
    'Daily' => 'ყოველდღიური',
    'Daily report' => 'ყოველდღიური ანგარიში',
    'Date' => 'თარიღი',
    'Day report' => 'ყოველდღიური ანგარიში',
    'Diagnostic Comms' => 'დიაგნოსტიკური შეტყობინებები',
    'Disconnect' => 'ზარალის კომუნიკაციის',
    'Export in 1C' => 'ექსპორტი 1C',
    'Export in Excel' => 'ექსპორტი Excel',
    'Export in Gasoline' => 'ექსპორტი Gasoline',
    'GRS' => 'გაზგამანაწილებელი სადგურის',
    'GSM modem' => 'GSM მოდემები',
    'History Limits' => 'ისტორიაში ლიმიტი',
    'HouseMetering' => 'სახლი გამრიცხველიანება ერთეული',
    'Indication' => 'მრიცხველის ჩვენების',
    'Indications table' => 'ჩვენებები მაგიდა',
    'Industry' => 'მრეწველობა',
    'Interventions' => 'ინტერვენციების',
    'Limit of this month' => 'შეზღუდვა ამ თვეში',
    'Limit the next month' => 'შეზღუდვა მომდევნო თვეში',
    'Limits of gas consumption' => 'შეზღუდვა გაზის მოხმარება',
    'List of correctors' => 'სია კორექტორების',
    'Map' => 'რუკა',
    'Modem' => 'მოდემი',
    'Monitoring' => 'მონიტორინგი',
    'Monthly' => 'ყოველთვიური',
    'Phone number' => 'ტელეფონის ნომერი',
    'Photo' => 'სურათი',
    'Pressure' => 'ზეწოლა',
    'Reports' => 'ანგარიშები',
    'Request for daily report' => 'მოთხოვნა ყოველდღიური ანგარიში',
    'Request for forced debiting' => 'მოთხოვნა სავალდებულო ფულადი სახსრების მოხსნის',
    'Request package name' => 'მოთხოვნა გვერდი პაკეტის სახელი',
    'Request to the corrector' => 'ინფორმაციის მოწოდების შესახებ თხოვნას კორექტორი',
    'Request to the simcard' => 'მოთხოვნა, რომ სიმ ბარათი',
    'Requests' => 'მოთხოვნა',
    'Signal level' => 'სიგნალი დონეზე',
    'Sleep' => 'ძილი',
    'Status' => 'მდგომარეობა',
    'Temperature' => 'ტემპერატურა',
    'Update time' => 'განახლება',
    'View' => 'მიმოხილვა',
    'Weekly' => 'ყოველკვირეული',
    'calculate' => 'გამოთვალეთ',
    'hw_status' => 'მდგომარეობა',
    'temperature' => 'ტემპერატურა',
];
