<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '% Of the limit applied <br> limit this month' => '% ლიმიტი გამოყენებული<br> ზღვარი ამ თვეში',
    'Accidents' => 'უბედური შემთხვევა',
    'Accidents in the past month' => 'უბედური შემთხვევა გასულ თვეში',
    'Consumption for the current day' => 'მოხმარების პოსტი დღეში',
    'Consumption for the month' => 'თვიური მოხმარება',
    'Consumption over the past day' => 'მოხმარების წინა დღეს',
    'Date' => 'თარიღი',
    'Delay' => '',
    'Diagnostic Comms' => 'დიაგნოსტიკური შეტყობინებები',
    'Interventions' => 'ინტერვენციების',
    'Modem number' => 'მოდემის ნომერი',
    'Off' => '',
    'On' => '',
    'Online mode' => '',
    'Pressure' => 'ზეწოლა',
    'Send' => '',
    'Send on' => '',
    'Temperature' => 'ტემპერატურა',
    'Time' => 'დრო',
    'Volume consumption' => 'მოცულობა მოხმარების',
    'not ready' => 'არ არის მზად',
    'online' => '',
    'ready' => 'მზად',
];
