<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'აქტიური',
    'Deactivated' => 'უმოქმედო',
    'Region' => 'რეგიონში',
    'Waiting_email_approve' => 'დადასტურებას ელ',
    'add_bot_in_contact_list' => 'დაამატეთ ბოტია თქვენს საკონტაქტო სიაში',
    'address' => 'მისამართი',
    'change_password' => 'შეცვალეთ თქვენი პაროლი',
    'chose_region' => 'აირჩიეთ ქალაქი',
    'email' => '',
    'enable_email_notif' => 'ჩართვა გაგზავნის შეტყობინებები ელ',
    'enable_telegram_notif' => 'ჩართვა გაგზავნის შეტყობინებები დეპეშები',
    'facility' => 'კომპანია',
    'first_name' => 'სახელი',
    'geo_location_id' => 'ქალაქი',
    'inn' => '',
    'last_name' => 'გვარი',
    'legal_address' => 'იურიდიული მისამართი',
    'main' => 'მთავარი',
    'new_password' => 'ახალი პაროლი',
    'nick_name' => 'მეტსახელად',
    'notification_types' => 'სახის შეტყობინებები',
    'notifications' => 'ცნობა',
    'password' => 'დაგავიწყდათ',
    'password_repeat' => 'გაიმეორეთ პაროლი',
    'reg_date' => 'რეგისტრაციის თარიღი',
    'role' => 'როლი',
    'roles' => 'როლი',
    'status' => 'მდგომარეობა',
    'telegram_id' => '',
    'user_edit' => 'რედაქტირება შესახებ',
    'users' => 'მომხმარებლების',
    'language_id'=>'ენის'
];
