<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Calendar' => '',
    'Contract' => '',
    'Indication' => '',
    'Monitoring' => '',
    'Options' => '',
    'Reports' => '',
    'Traffic' => '',
    'invoice' => '',
    'indication' => '@@Indications@@',
    'monitoring' => '@@Monitoring@@',
    'options' => '@@Settings@@',
    'reports' => '@@Reports@@',
    'Accidents' => 'Accidents',
    'Charts' => 'Charts',
    'ConsumpCurrentDay' => 'Consumption for the current day',
    'ConsumpDayAverage' => 'Average daily consumption',
    'ConsumpMonth' => 'Consumption for the month',
    'ConsumpPastDay' => 'Consumption over the past day',
    'Contractor' => 'Contractor',
    'Counter' => 'Counter',
    'GSM modem' => 'GSM modem',
    'Map' => 'Map',
    'account' => 'Account',
    'alerts_log' => 'Alerts Log',
    'balance' => 'On account',
    'chose_address' => 'Select address',
    'close' => 'Closed',
    'close_valve' => 'close valve',
    'command_send_in' => 'command sent in',
    'consump' => 'Consumption',
    'counter_number' => 'Counter number',
    'created_at' => 'created',
    'currentDate' => 'Current Date',
    'currentIndications' => 'Current indications',
    'current_indication' => 'Current indications',
    'download' => 'Download',
    'export_csv' => 'Export в CSV',
    'export_dbf' => 'Export DBF',
    'fulladdress' => 'Address',
    'geo_location_id' => 'Address',
    'history_indiations' => 'Indications history',
    'metrix_list' => 'List of counters',
    'modem' => 'modem',
    'modem_number' => 'Modem number',
    'open' => 'open',
    'open_valve' => 'Open Valve',
    'period_begin' => 'Start time',
    'period_end' => 'End of the period',
    'phone' => 'Phone',
    'report_for' => 'Report',
    'sform' => 'Generate',
    'signal_level' => 'Signal Level',
    'status' => 'Status',
    'time_on_line' => 'Last online',
    'updated_at' => 'Updated at',
    'valve_status' => 'Valve status',
    'view' => 'view',
    'modem_options'=>'Modem Options',
    'update_interval'=>'Update Interval (MINUTES!)',
    'Query send in {time}'=>'',
];
