<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Deactivated' => '',
    'Region' => '',
    'Waiting_email_approve' => 'Waiting email approve',
    'add_bot_in_contact_list' => 'add bot in contact list',
    'address' => '',
    'change_password' => 'Change password',
    'chose_region' => 'Chose region',
    'email' => 'email',
    'enable_email_notif' => 'Enable email',
    'enable_telegram_notif' => 'Enable telegram',
    'facility' => '',
    'first_name' => 'first name',
    'geo_location_id' => 'City',
    'inn' => '',
    'last_name' => 'Last name',
    'legal_address' => 'Legal address',
    'main' => 'Main',
    'new_password' => 'New password',
    'nick_name' => 'Nick name',
    'notification_types' => 'Notification types',
    'notifications' => 'Notifications',
    'password' => 'password',
    'password_repeat' => 'Password repeat',
    'reg_date' => 'reg_date',
    'role' => 'role',
    'roles' => 'Roles',
    'status' => 'status',
    'telegram_id' => 'telegram id',
    'user_edit' => ' User editing',
    'users' => 'Users',
    'language_id'=>'Language'
];
