<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Chose User type' => 'Chose User type',
    'Chose city' => 'Chose city',
    'Chose region' => 'Chose region',
    'City' => 'City',
    'Flat indications' => 'Indications for period',
    'House metering station' => 'House metering station',
    'ID' => 'ID',
    'Individual' => 'Individual',
    'Legal entity' => 'Legal entity',
    'Modem id' => 'Modem id',
    'Reset filter' => 'Reset ',
    'Submit filter' => 'Submit ',
    'Type' => 'Type',
    'User id' => 'User id',
    'User type' => 'User type',
    'account' => 'Account',
    'battery_level' => 'Battery level',
    'counter_model' => 'Counter model',
    'created_at' => 'Created at',
    'flat' => 'Flat',
    'fulladdress' => 'Address',
    'fulladdresswithcity' => 'Address',
    'fullname' => 'Fullname',
    'geo_location_id' => 'Address',
    'identifier' => 'Identifier',
    'initial_indications' => 'Initial indications',
    'is_ignore_alert' => 'Alert ignore',
    'last_indications' => 'Last indications',
    'month_update' => 'Monthly update',
    'real_serial_number' => 'Counter serial number',
    'resizedImage' => 'Resized image',
    'rmodule_id' => 'Radiomodule number',
    'serial_number' => 'serial number',
    'tamper_detect' => '',
    'tamper_detect_key' => '',
    'update_interval' => 'Update interval',
    'updated_at' => 'Updated at',
    'Search' => 'Search',
    'Search query' => 'Search query',
    'Map' => '',
];
