<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Average pressure, kgf / m<sup>2</sup>' => 'Average pressure, kgf / m<sup>2</sup>',
    'Average temperature C<sup>o</sup>' => 'Average temperature C<sup>o</sup>',
    'Consumption over the past day s.c. ,m<sup>3</sup>' => 'Consumption over the past day s.c. ,m<sup>3</sup>',
    'Consumption over the past hour s.c. ,m<sup>3</sup>' => 'Consumption over the past hour s.c. ,m<sup>3</sup>',
    'Consumption per day s.c. ,m<sup>3</sup>' => 'Consumption per day s.c. ,m<sup>3</sup>',
    'Consumption per hour s.c. ,m<sup>3</sup>' => 'Consumption per hour s.c. ,m<sup>3</sup>',
    'Diameter ND , mm' => 'Diameter ND , mm',
    'Diameter Tube, mm' => 'Diameter Tube, mm',
    'Differential pressure, kgf / m<sup>2</sup>' => 'Differential pressure, kgf / m<sup>2</sup>',
    'Pressure, kgf / m<sup>2</sup>' => 'Pressure, kgf / m<sup>2</sup>',
    'Pseudocritical pressure, kgf / m<sup>2</sup>' => 'Pseudocritical pressure, kgf / m<sup>2</sup>',
    'Pseudocritical temperature C<sup>o</sup>' => 'Pseudocritical temperature C<sup>o</sup>',
    'Temperature C<sup>o</sup>' => 'Temperature C<sup>o</sup>',
    'Updated at' => 'Updated at',
    'Volume consumption r.c.' => 'Volume consumption r.c.',
    'Volume consumption s.c.' => 'Volume consumption s.c.',
];
