<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Balance' => '',
    'Balance history' => '',
    'Calculator number' => '',
    'Charts' => '',
    'Combit' => '',
    'Connect log' => '',
    'Consumption on day' => '',
    'Consumption on prev day' => '',
    'Contract' => '',
    'Contract hour' => '',
    'Contractor' => '',
    'Current pressure' => '',
    'Current temperature' => '',
    'Cycle ' => '',
    'Daily' => '',
    'Daily report' => '',
    'Data for' => '',
    'Date' => '',
    'Day report' => '',
    'Diagnostic Comms' => '',
    'Export in 1C' => '',
    'Export in Excel' => '',
    'Export in Gasoline' => '',
    'GSM modem' => '',
    'History Limits' => '',
    'Indication' => '',
    'Industry' => '',
    'Interventions' => '',
    'Last online' => '',
    'Limit of this month' => '',
    'Limit the next month' => '',
    'Limits of gas consumption' => '',
    'List of correctors' => '',
    'Map' => '',
    'Modem' => '',
    'Monitoring' => '',
    'Monthly' => '',
    'Phone number' => '',
    'Photo' => '',
    'Pressure' => '',
    'Reports' => '',
    'Request for daily report' => '',
    'Request for forced debiting' => '',
    'Request package name' => '',
    'Request to the corrector' => '',
    'Request to the simcard' => '',
    'Requests' => '',
    'SIM' => '',
    'SMS history' => '',
    'Signal level' => '',
    'Temperature' => '',
    'The query is executed expect an answer' => '',
    'Update time' => '',
    'View' => '',
    'Weekly' => '',
    'hw_status' => '',
    'Corrector list' => '@@List of correctors@@',
    'action' => '@@action@@',
    'consumption on day' => '@@consumption on day@@',
    'consumption on prev day' => '@@consumption on prev day@@',
    'day report' => '@@day report@@',
    'pressure' => '@@pressure@@',
    'temperature' => '@@temperature@@',
    'update time' => '@@update time@@',
    'view' => '@@view@@',
    'Accidents' => 'Accidents',
    'Action' => 'Action',
    'Address' => 'Address1',
    'Company' => 'Company',
    'Company name' => 'Company name',
    'ConsumpTotal' => 'Total consumption',
    'CreateReport' => 'Create report',
    'GRS' => 'Gas distribution stations',
    'HouseMetering' => 'House metering station',
    'Indications table' => 'Indications table',
    'Status' => 'Status',
];
