<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "search".
 *
 * @property integer $id
 * @property string $search_string
 * @property double $counter_id
 * @property string $created_at
 * @property string $type
 */
class Search extends \yii\db\ActiveRecord
{
    public $label;
    public $value;
    /**
     * @inheritdoc
     */

    public function afterFind()
    {

        parent::afterFind(); // TODO: Change the autogenerated stub

    }




    public static function tableName()
    {
        return 'search';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['counter_id'], 'number'],
            [['created_at'], 'safe'],
            [['search_string'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'search_string' => 'Search String',
            'counter_id' => 'Counter ID',
            'created_at' => 'Created At',
        ];
    }
}
